name: admin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #common
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  flutter_svg: ^2.1.0
  nb_utils: ^7.1.4
  uuid: ^4.5.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  html: ^0.15.6
  provider: ^6.1.5
  aligned_dialog: ^0.0.7
  flex_color_picker: ^3.7.1
  url_strategy: ^0.3.0
  syncfusion_flutter_charts: ^29.2.10
  flutter_easyloading: ^3.0.5
  file_picker: ^10.2.0
  flutter_custom_text_input_formatter: ^0.0.4
  location: ^8.0.0
  timelines_plus: ^1.0.7
  syncfusion_flutter_datepicker:
  pdf: ^3.11.3
  open_file: ^3.5.10
  universal_html: ^2.2.4
  excel: ^4.0.6
  dropdown_search: ^6.0.2

  #Firebase
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7

  html_editor_enhanced:
    path: ./html_editor_enhanced

dependency_overrides:
  intl: ^0.20.2
  web: ^1.1.1
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/image/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf

    - family: Inter-ExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

    - family: Recoleta-SemiBold
      fonts:
        - asset: assets/fonts/Recoleta-SemiBold.ttf
