name: customer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutterflow_paginate_firestore: ^1.0.3+1
  firebase_storage: ^12.4.9
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.3.0
  auto_size_text_field: ^2.2.4
  syncfusion_flutter_datepicker: ^30.1.38

 #pdf
  pdf: ^3.11.3
  open_file: ^3.5.10
  excel: ^4.0.6

  get: ^4.7.2
  provider: ^6.1.5
  http_auth: ^1.0.4
  country_code_picker: ^3.3.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1

  pinput: ^5.0.1

  crypto: ^3.0.6
  intl: ^0.20.2

  timelines_plus: ^1.0.7
  path_provider: ^2.1.5

#  google_places_flutter: ^2.0.8
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.12.3
  location: ^8.0.1
#  map_launcher: ^3.5.0 //non-used

  geocoding: ^4.0.0
  geoflutterfire2: ^2.3.15
  googleapis_auth: ^2.0.0
  dio: ^5.8.0+1
  uuid: ^4.5.1

  http: ^1.4.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  flutter_widget_from_html: ^0.16.0
  flutter_rating_bar: ^4.0.1
#  lottie: ^3.1.3 //non-used
  permission_handler: ^12.0.1

  #payment_dependencies
  flutter_stripe: ^11.5.0
#  flutter_paypal_native: ^2.1.0
  razorpay_flutter: ^1.4.0
  mp_integration: ^0.0.1
  url_launcher: ^6.3.1
  dotted_border: ^3.1.0
  fluttertoast: ^8.2.12

dependency_overrides:
  web: ^1.1.1
  rxdart: ^0.28.0
  cloud_firestore: ^5.6.11
  package_info_plus: ^8.3.0
  geolocator: ^14.0.2
  google_maps_place_picker_mb: ^3.1.2
  google_api_headers: ^4.5.4
#  flutterwave_standard: ^1.0.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/animation/
